export const PREMIUM_BRANDS = [
  { imgSrc: "/images/audi.png", brand: "Audi" },
  { imgSrc: "/images/bmw.png", brand: "BMW" },
  { imgSrc: "/images/ford.png", brand: "Ford" },
  { imgSrc: "/images/mercedes-benz.png", brand: "Mercedes-Benz" },
  { imgSrc: "/images/nissan.png", brand: "Nissan" },
  { imgSrc: "/images/volkswagen.png", brand: "Volkswagen" },
];

export const BRAND_IMAGES: Record<string, string> = {
  Acura: "/images/acura.png",
  "Alfa Romeo": "/images/alfa-romeo.png",
  "Aston Martin": "/images/aston-martin.png",
  Audi: "/images/audi.png",
  Bentley: "/images/bentley.png",
  BMW: "/images/bmw.png",
  Buick: "/images/buick.png",
  Cadillac: "/images/cadillac.png",
  Chevrolet: "/images/chevrolet.png",
  Chrysler: "/images/chrysler.png",
  Dodge: "/images/dodge.png",
  Ferrari: "/images/ferrari.png",
  Fiat: "/images/fiat.png",
  Ford: "/images/ford.png",
  Genesis: "/images/genesis.png",
  GMC: "/images/gmc.png",
  Honda: "/images/honda.png",
  Hyundai: "/images/hyundai.png",
  Infiniti: "/images/infiniti.png",
  Jaguar: "/images/jaguar.png",
  Jeep: "/images/jeep.png",
  Kia: "/images/kia.png",
  Lamborghini: "/images/lamborghini.png",
  "Land Rover": "/images/land-rover.png",
  Lexus: "/images/lexus.png",
  Lincoln: "/images/lincoln.png",
  Lucid: "/images/lucid.png",
  Maserati: "/images/maserati.png",
  Mazda: "/images/mazda.png",
  McLaren: "/images/mclaren.png",
  "Mercedes-Benz": "/images/mercedes-benz.png",
  MINI: "/images/mini.png",
  Mitsubishi: "/images/mitsubishi.png",
  Nissan: "/images/nissan.png",
  Polestar: "/images/polestar.png",
  Porsche: "/images/porsche.png",
  Ram: "/images/ram.png",
  Rivian: "/images/rivian.png",
  "Rolls-Royce": "/images/rolls-royce.png",
  Scion: "/images/scion.png",
  Smart: "/images/smart.png",
  Subaru: "/images/subaru.png",
  Suzuki: "/images/suzuki.png",
  Tesla: "/images/tesla.png",
  Toyota: "/images/toyota.png",
  Volkswagen: "/images/volkswagen.png",
  Volvo: "/images/volvo.png",
};

export const FEATURED_MODELS = [
  { id: 1, value: "Sonata", imgSrc: "/images/SUV.png" },
  { id: 2, value: "Civic", imgSrc: "/images/SUV.png" },
  { id: 3, value: "Sentra", imgSrc: "/images/SUV.png" },
  { id: 4, value: "Corolla", imgSrc: "/images/SUV.png" },
  { id: 5, value: "Malibu", imgSrc: "/images/SUV.png" },
];

export const MODEL_OPTIONS: { [key: string]: string[] } = {
  Acura: ["RDX", "TLX"],
  "Alfa Romeo": ["Giulia"],
  "Aston Martin": ["DB11"],
  Audi: ["A4", "Q5", "Q7", "RS e-tron GT"],
  Bentley: ["Continental GT"],
  BMW: ["3 Series", "5 Series", "i3", "i4", "M3", "X3", "X5"],
  Buick: ["Enclave"],
  Cadillac: ["CT5"],
  Chevrolet: [
    "Blazer",
    "Bolt EV",
    "Camaro",
    "Equinox",
    "Impala",
    "Malibu",
    "Spark",
  ],
  Chrysler: ["300"],
  Dodge: ["Challenger"],
  Ferrari: ["F8"],
  Fiat: ["500X"],
  Ford: [
    "Escape",
    "Explorer",
    "F-150",
    "F-150 Lightning",
    "Focus",
    "Fusion",
    "Mustang",
  ],
  Genesis: ["G80"],
  GMC: ["Sierra"],
  Honda: ["Accord", "Civic", "Civic Type R", "CR-V", "Fit", "Insight", "Pilot"],
  Hyundai: ["Accent", "Elantra", "Palisade", "Sonata", "Tucson"],
  Infiniti: ["Q50"],
  Jaguar: ["F-Type"],
  Jeep: ["Cherokee", "Grand Cherokee", "Wrangler"],
  Kia: ["Forte", "K5", "Optima", "Rio", "Sportage", "Stinger", "Telluride"],
  Lamborghini: ["Huracan"],
  Lexus: ["ES", "GX", "RX"],
  Lincoln: ["Navigator"],
  Lucid: ["Air"],
  Maserati: ["Ghibli"],
  Mazda: ["CX-30", "CX-5", "CX-9", "Mazda3", "Mazda6", "MX-5 Miata"],
  McLaren: ["720S"],
  "Mercedes-Benz": ["AMG GT", "C-Class", "GLC", "GLE"],
  Mini: ["Cooper"],
  Mitsubishi: ["Eclipse Cross"],
  Nissan: ["Altima", "GT-R", "Leaf", "Pathfinder", "Rogue", "Sentra", "Versa"],
  Polestar: ["2"],
  Porsche: ["911", "Cayenne", "Taycan"],
  Ram: ["1500"],
  Rivian: ["R1T"],
  "Rolls-Royce": ["Ghost"],
  Scion: ["tC"],
  Smart: ["ForTwo"],
  Subaru: ["Ascent", "BRZ", "Forester", "Impreza", "Legacy", "Outback"],
  Suzuki: ["Vitara"],
  Tesla: ["Cybertruck", "Model 3", "Model S", "Model Y"],
  Toyota: ["Camry", "Corolla", "Highlander", "RAV4", "Supra", "Yaris"],
  Volkswagen: ["Atlas", "Golf", "Golf R", "ID.4", "Jetta", "Polo", "Tiguan"],
  Volvo: ["XC90"],
};
