export const PREMIUM_BRANDS = [
  { imgSrc: "/images/audi.png", brand: "Audi" },
  { imgSrc: "/images/bmw.png", brand: "BMW" },
  { imgSrc: "/images/ford.png", brand: "Ford" },
  { imgSrc: "/images/mercedes-benz.png", brand: "Mercedes-Benz" },
  { imgSrc: "/images/nissan.png", brand: "Nissan" },
  { imgSrc: "/images/volkswagen.png", brand: "Volkswagen" },
];

export const BRAND_IMAGES: Record<string, string> = {
  Audi: "/images/audi.png",
  BMW: "/images/bmw.png",
  Ford: "/images/ford.png",
  "Mercedes-Benz": "/images/mercedes-benz.png",
  Nissan: "/images/nissan.png",
  Volkswagen: "/images/volkswagen.png",
  Tesla: "/images/tesla.png",
};

export const FEATURED_MODELS = [
  { id: 1, value: "Sonata", imgSrc: "/images/SUV.png" },
  { id: 2, value: "Civic", imgSrc: "/images/SUV.png" },
  { id: 3, value: "Sentra", imgSrc: "/images/SUV.png" },
  { id: 4, value: "Corolla", imgSrc: "/images/SUV.png" },
  { id: 5, value: "Malibu", imgSrc: "/images/SUV.png" },
];

export const MODEL_OPTIONS: { [key: string]: string[] } = {
  Acura: ["RDX", "TLX"],
  "Alfa Romeo": ["Giulia"],
  "Aston Martin": ["DB11"],
  Audi: ["A4", "Q5", "Q7", "RS e-tron GT"],
  Bentley: ["Continental GT"],
  BMW: ["3 Series", "5 Series", "i3", "i4", "M3", "X3", "X5"],
  Buick: ["Enclave"],
  Cadillac: ["CT5"],
  Chevrolet: [
    "Blazer",
    "Bolt EV",
    "Camaro",
    "Equinox",
    "Impala",
    "Malibu",
    "Spark",
  ],
  Chrysler: ["300"],
  Dodge: ["Challenger"],
  Ferrari: ["F8"],
  Fiat: ["500X"],
  Ford: [
    "Escape",
    "Explorer",
    "F-150",
    "F-150 Lightning",
    "Focus",
    "Fusion",
    "Mustang",
  ],
  Genesis: ["G80"],
  GMC: ["Sierra"],
  Honda: ["Accord", "Civic", "Civic Type R", "CR-V", "Fit", "Insight", "Pilot"],
  Hyundai: ["Accent", "Elantra", "Palisade", "Sonata", "Tucson"],
  Infiniti: ["Q50"],
  Jaguar: ["F-Type"],
  Jeep: ["Cherokee", "Grand Cherokee", "Wrangler"],
  Kia: ["Forte", "K5", "Optima", "Rio", "Sportage", "Stinger", "Telluride"],
  Lamborghini: ["Huracan"],
  Lexus: ["ES", "GX", "RX"],
  Lincoln: ["Navigator"],
  Lucid: ["Air"],
  Maserati: ["Ghibli"],
  Mazda: ["CX-30", "CX-5", "CX-9", "Mazda3", "Mazda6", "MX-5 Miata"],
  McLaren: ["720S"],
  "Mercedes-Benz": ["AMG GT", "C-Class", "GLC", "GLE"],
  Mini: ["Cooper"],
  Mitsubishi: ["Eclipse Cross"],
  Nissan: ["Altima", "GT-R", "Leaf", "Pathfinder", "Rogue", "Sentra", "Versa"],
  Polestar: ["2"],
  Porsche: ["911", "Cayenne", "Taycan"],
  Ram: ["1500"],
  Rivian: ["R1T"],
  "Rolls-Royce": ["Ghost"],
  Scion: ["tC"],
  Smart: ["ForTwo"],
  Subaru: ["Ascent", "BRZ", "Forester", "Impreza", "Legacy", "Outback"],
  Suzuki: ["Vitara"],
  Tesla: ["Cybertruck", "Model 3", "Model S", "Model Y"],
  Toyota: ["Camry", "Corolla", "Highlander", "RAV4", "Supra", "Yaris"],
  Volkswagen: ["Atlas", "Golf", "Golf R", "ID.4", "Jetta", "Polo", "Tiguan"],
  Volvo: ["XC90"],
};
